import getEnvVars from "../../environment";

const {
  REACT_NATIVE_ANDROID_FIREBASE_API_KEY,
  REACT_NATIVE_ANDROID_FIREBASE_AUTHDOMAIN,
  REACT_NATIVE_ANDROID_FIREBASE_PROJECT_ID,
  REACT_NATIVE_ANDROID_FIREBASE_STORAGE_BUCKET,
  REACT_NATIVE_ANDROID_FIREBASE_MESSAGING_SENDER_ID,
  REACT_NATIVE_ANDROID_FIREBASE_APP_ID,
  REACT_NATIVE_ANDROID_MEASUREMENT_ID,
} = getEnvVars();

export const firebaseConfig = {
  apiKey: REACT_NATIVE_ANDROID_FIREBASE_API_KEY,
  authDomain: REACT_NATIVE_ANDROID_FIREBASE_AUTHDOMAIN,
  projectId: REACT_NATIVE_ANDROID_FIREBASE_PROJECT_ID,
  storageBucket: REACT_NATIVE_ANDROID_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: REACT_NATIVE_ANDROID_FIREBASE_MESSAGING_SENDER_ID,
  appId: REACT_NATIVE_ANDROID_FIREBASE_APP_ID,
  measurementId: REACT_NATIVE_ANDROID_MEASUREMENT_ID,
};
